### ISSUE TITLE
ID deputy

### ISSUE THREAD

**Issue by beastie87** [OPORA/scraper_lviv_deputy-#2]
Нажаль на оф сайті не має загально прийнятого айді депутата тому виникає наступне питання:
Яким чином призначати айді депутата? 
робити просто довільне id чи (гуід ід) gid?

**Comment by beastie87** [comment]
на сайті є айді контенту, може використати його ? `/component/k2/item/3463-kuzheliuk-yurii-anatoliiovych-gromadianska-pozytsia`

**Comment by lisoffsky** [comment]
теж бачив ІД контенту. 
А якщо в кількох містах в нас буде однакове айді? Може якісь свої присвоїти? місто-ід, де міста шифрувати номерами від першого запущеного проекту? Львів -1 ...

**Comment by beastie87** [comment]
Ну в нас кожне місто матиме свою базу

**Comment by beastie87** [comment]
яке ж айді присвоїти Садовому?)

**Comment by beastie87** [comment]
1111 - це буде мер міста
